name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Prepare Theos
      uses: Randomblock1/theos-action@v0
      with:
        theos-sdks: 'https://github.com/xybp888/iOS-SDKs'
      
    - name: actual build
      run: |
        rm -f packages/*
        make package FINALPACKAGE=1
    - name: upload deb
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'Package'
        path: ${{ github.workspace }}/packages/*.deb
